# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: Essentials
main: com.earth2me.essentials.Essentials
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${project.version}
website: http://www.earth2me.net:8001/
description: Provides an essential, core set of commands for Bukkit.
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits]
softdepend: [Fundamentals, JPerms]
commands:
  afk:
    description: Marks you as away-from-keyboard.
    usage: /<command>
    aliases: [eafk]
#  antioch:
#    description: 'A little surprise for operators.'
#    usage: /<command>
#    aliases: [eantioch]
  back:
    description: Teleports you to your location prior to tp/spawn/warp.
    usage: /<command>
  backup:
    description: Runs the backup if configured.
    usage: /<command>
  balance:
    description: States the current balance of a player.
    usage: /<command> <player>
    aliases: [bal]
  balancetop:
    description: Gets the top x balance values. (max 10)
    usage: /<command> <max>
    aliases: [baltop]
  ban:
    description: Bans a player.
    usage: /<command> [player] <reason>
    aliases: [eban]
  banip:
    description: Bans an IP address.
    usage: /<command> [address]
    aliases: [ebanip]
  broadcast:
    description: Broadcasts a message to the entire server.
    usage: /<command> [msg]
  bigtree:
    description: Spawn a big tree where you are looking.
    usage: /<command> [tree|redwood]
  burn:
    description: Set a player on fire.
    usage: /<command> [player] [seconds]
  clearinventory:
    description: Clear all items in your inventory.
    usage: /<command>
    aliases: [ci]
  compass:
    description: Describes your current bearing.
    usage: /<command>
  delhome:
    description: Removes a home
    usage: /<command> [player] <name>
    aliases: [remhome,rmhome]
  deljail:
    description: Removes a jail
    usage: /<command> [jailname]
  dellost:
    description: Deletes the specified lost and found warp.
    usage: /<command> [warp]
  delwarp:
    description: Deletes the specified warp.
    usage: /<command> [warp]
    aliases: [remwarp,rmwarp]
  depth:
    description: States current depth, relative to sea level.
    usage: /depth
  eco:
    description: Manages the server economy.
    usage: /<command> [give|take|reset] [player] [amount]
    aliases: [economy]
  essentials:
    description: Reloads essentials.
    usage: /<command>
  ext:
    description: Extinguish players.
    usage: /<command> <player>
    aliases: [extinguish,eext]
  fireball:
    description: Throw a fireball.
    usage: /<command>
  getpos:
    description: Get your current coordinates.
    usage: /<command>
    aliases: [coords]
  gc:
    description: Reports garbage collection info; useful to developers.
    usage: /<command>
    aliases: [mem,memory]
  give:
    description: Give a player an item.
    usage: /<command> [player] [item|numeric] <amount>
  god:
    description: Enables your godly powers.
    usage: /<command>
    aliases: [tgm,godmode,egod,egodmode,etgm]
  heal:
    description: Heals you or the given player.
    usage: /<command> <player>
  help:
    description: Views a list of available commands.
    usage: /<command> [search term] [page]
#  helpop:
#    description: Request help from online operators.
#    usage: /<command> [message]
#    aliases: [ehelpop]
  home:
    description: Teleport to your home.
    usage: /<command> <player>
  ignore:
    description: Ignore other players.
    usage: /<command> <player>
  ignorelist:
    description: Lists your ignored players.
    usage: /<command>
  info:
    description: Shows information set by the server owner
    usage: /<command> [chapter] [page]
    aliases: [ifo,einfo,eabout,news,enews,eifo]
  invsee:
    description: See the inventory of other players.
    usage: /<command> <player>
  item:
    description: Spawn an item.
    usage: /<command> [item|numeric] <amount>
    aliases: [i]
  jails:
    description: List all jails.
    usage: /<command>
  jump:
    description: Jumps to the nearest block in the line of sight.
    usage: /<command>
    aliases: [j,ejump]
  kick:
    description: Kicks a specified player with a reason.
    usage: /<command> <player> <reason>
    aliases: [ekick]
  kickall:
    description: Kicks all players off the server except the issuer.
    usage: /<command> <reason>
  kit:
    description: Obtains the specified kit or views all available kits.
    usage: /<command> <kit>
    aliases: [kits]
  kill:
    description: Kills specified player.
    usage: /<command> <player>
  list:
    description: List all online players.
    usage: /<command>
    aliases: [playerlist,who,online]
  lightning:
    description: The power of Thor. Strike at cursor or player.
    usage: /<command> [player]
    aliases: [strike,smite]
  lost:
    description: Teleports to the specified location in lost and found
    usage: /<command> [warp]
  mail:
    description: Manages inter-player, intra-server mail.
    usage: /<command> [read|clear|send [to] [message]]
    aliases: [email]
#  me:
#    description: Describes an action in the context of the player.
#    usage: /<command> [description]
#    aliases: [eme]
  motd:
    description: Views the Message Of The Day.
    usage: /<command>
  msg:
    description: Sends a private message to the specified player.
    usage: /<command> <to> <message>
    aliases: [m,t,emsg,tell]
  mute:
    description: Mutes or unmutes a player.
    usage: /<command> [player] <datediff>
  nick:
    description: Change your nickname or that of another player.
    usage: /<command> <player> [nickname|off]
  nuke:
    description: May death rain upon them.
    usage: /<command> <player>
  pay:
    description: Pays another player from your balance
    usage: /<command> [player] [amount]
  ping:
    description: Pong!
    usage: /<command>
    aliases: [pong]
  powertool:
    description: Assigns a command to the item in hand, {player} will be replaced by the name of the player that you click.
    usage: /<command> [l:|a:|r:][command] <arguments>
    aliases: [pt,epowertool,ept]
  ptime:
    description: Adjust player's client time. Add @ prefix to fix.
    usage: /<command> [list|reset|day|night|dawn|17:30|4pm|4000ticks] <player|*>
    aliases: [playertime]
  r:
    description: Quickly reply to the last player to message you.
    usage: /<command> [message]
    aliases: [reply]
  realname:
    description: Displays the username of a user based on nickname.
    usage: /<command> [nickname]
  reloadall:
    description: Reloads all plugins.
    usage: /<command>
    aliases: [rel,ereloadall,ereload,erel]
  repair:
    description: Repairs the durability of all or one item.
    usage: /<command> [hand|all]
    aliases: [fix]
  rules:
    description: Views the server rules.
    usage: /<command>
  seen:
    description: Shows the last logout time of a player
    usage: /<command> [playername]
  sell:
    description: Sells the item currently in your hand.
    usage: /<command> [itemname|id|hand|inventory|blocks] [-][amount]
  sethome:
    description: Set your home to your current location.
    usage: /<command>
  setjail:
    description: Creates a jail where you specified named [jailname]
    usage: /<command> [jailname]
  setlost:
    description: Creates a new lost and found warp.
    usage: /<command> [warp]
  setwarp:
    description: Creates a new warp.
    usage: /<command> [warp]
    aliases: [createwarp]
  setworth:
    description: Set the sell value of an item.
    usage: /<command> [itemname|id] [price]
  socialspy:
    description: Toggles if you can see msg/mail commands in chat.
    usage: /<command>
    aliases: [ss,social]
  spawner:
    description: Change the mob type of a spawner
    usage: /<command> [mob]
  spawnmob:
    description: Spawns a mob.
    usage: /<command> [mob]<:data><,mount<:data>> <amount>
  suicide:
    description: Causes you to perish.
    usage: /<command>
  tempban:
    description: Temporary ban a user.
    usage: /<command> [playername] [datediff]
    aliases: [etempban]
  thunder:
    description: Enable/disable thunder.
    usage: /<command> <true/false> [duration]
  time:
    description: Change the world time. Defaults to current world.
    usage: /<command> [day|night|dawn|17:30|4pm|4000ticks] [worldname|all]
    aliases: [etime, day, night]
  togglejail:
    description: Prevents a player from interacting with the world and teleports him/her to the the jail specified
    usage: /<command> [player] [jailname] <datediff>
    aliases: [tjail]
  top:
    description: Teleport to the highest block at your current position.
    usage: /<command>
  tp:
    description: Teleport to a player.
    usage: /<command> [player]
  tpa:
    description: Request to teleport to the specified player.
    usage: /<command> <player>
  tpaall:
    description: Requests all players online to teleport to you.
    usage: /<command> <player>
  tpaccept:
    description: Accepts a teleport request.
    usage: /<command>
  tpahere:
    description: Request that the specified player teleport to you.
    usage: /<command> <player>
  tpall:
    description: Teleport all online players to another player.
    usage: /<command> <player>
  tpdeny:
    description: Reject a teleport request.
    usage: /<command>
  tphere:
    description: Teleport a player to you.
    usage: /<command> [player]
  tpo:
    description: Teleport override for tptoggle.
    usage: /<command> <player>
  tpohere:
    description: Teleport here override for tptoggle.
    usage: /<command> <player>
  tppos:
    description: Teleport to coordinates.
    usage: /<command> <x> <y> <z>
  tptoggle:
    description: Blocks all forms of teleportation.
    usage: /<command>
  tree:
    description: Spawn a tree where you are looking.
    usage: /<command> [tree|birch|redwood]
  unban:
    description: Unbans the specified player.
    usage: /<command> [player]
    aliases: [pardon,eunban]
  unbanip:
    description: Unbans the specified IP address.
    usage: /<command> [address]
    aliases: [eunbanip,pardonip]
  unlimited:
    description: Allows the unlimited placing of items.
    usage: /<command> [list|item] <player>
    aliases: [ul,unl,eul]
  warp:
    description: List all warps or warp to the specified location.
    usage: /<command> [pagenumber|warp] <player>
    aliases: [warps]
  weather:
    description: Setting the weather.
    usage: /<command> <storm/sun> [duration]
    aliases: [sky,sun,storm]
  whois:
    description: Determine the username behind a nickname.
    usage: /<command> [nickname]
  world:
    description: Switch between worlds.
    usage: /<command> [world]
  worth:
    description: Calculates the worth of items in hand or as specified.
    usage: /<command> <item> <amount>
